# Global settings applied to the whole site
[build]
  # Base directory to run the build command
  # This is relative to the root of your repository
  base = "client/"

  # Combined build command
  # Adjust this command to your needs. This is just an example.
  # This example assumes you have a script named `build-functions` in your `server` package.json
  # that prepares your server for deployment, and a similar setup for your client.
  command = "npm install && npm run build && npm run export && cd ../server && npm install && npm run build-functions"

  # Directory to publish (the output of your build command for the client)
  publish = "client/out"

  # Environment variables for the build environment
  [build.environment]
    NODE_VERSION = "14"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions settings
[functions]
  # Directory to store your serverless functions
  directory = "netlify/functions"

# Setting up environment variables for functions
[functions.environment]
    DB_USER = "postgres"
    DB_HOST = "localhost"
    DB_NAME = "learnlinkdb"
    DB_PASSWORD = "postgres"
    DB_PORT = 5432
