import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'semantic-ui-css/semantic.min.css'
import { AccountProvider } from "@/context/AccountContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "learnlink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AccountProvider>
        <body className={inter.className}>{children}</body>
      </AccountProvider>
    </html>
  );
}
